### ISSUE TITLE
unknown(0,0): unable to locate script <scriptname>

### ISSUE THREAD

**Issue by Feuerkl1nge** [Kiyozz/papyrus-compiler-app#81]
- Windows 10 x64 Pro 20H2
- Creation Kit and it's up to date script sources installed correctly and overwritten with the skse ones.
- PCA settings are set correctly.
- Because PCA doesn't recognize MO2's virtual directory, the source scripts are located in a custom directory. (without UAC enforcement)
- I tried with and without admin rights.
- I tried it with PCA running within and without MO2. Always with correct PCA settings.
- I use latest version 5.2.0

![vDMnWyEEjr](https://user-images.githubusercontent.com/64936130/106568666-df5bb980-6533-11eb-8173-5d1389e05d50.jpg)

**Comment by Kiyozz** [comment]
1. Has PCA worked with you at least once before?
2. Are you using the "MO2" option in the settings? And how do you start PCA if so
3. What are your "correct settings"?
4. What do you mean by custom scripts folder?

This error says that EpicRestorationHolinessScript.psc script was not found in the final Source\Scripts or Scripts\Source folder of MO2

**Comment by Feuerkl1nge** [comment]
It has worked now. I had to have the source scripts within the Skyrim SE installation.

I didn't try that at first, because with PCA I have no access to the virtual installation of MO2.
Even if I start PCA within MO2 with PCA's correct settings for that.
So I had to manually put the source scripts to Skyrim SE's scripts directory. It's not optimal, but anyway a nice app.

**Comment by Kiyozz** [comment]
Hum, strange because normally, with the virtual environment of MO2, everything is grouped / merged in the game folder.

So the papyrus compiler should work.

I remind you that here is a message from PapyrusCompiler and not from PCA

**Comment by Feuerkl1nge** [comment]
Maybe because I use the archive version of MO2 with a portable instance for SSE and the non installer version of PCA.

**Comment by Kiyozz** [comment]
I personally use .7z version of PCA with portable instance of MO2. All MO2 folders (mods, downloads, profiles) are in the portable instance. I do not edit MO2 folders settings
